version: '3'
services:
  postdb1:
    container_name: postdb1
    restart: unless-stopped
    image: postgres:9.6
    volumes:
      - ${WORKDIR}/docker/postgresql:/var/lib/postgresql/data
      - ~/etc/timezone:/etc/localtime:ro
    environment:
      - POSTGRES_USER='root'
      - POSTGRES_PASSWORD='root'
    ports:
      - "5432:5432"
  influxdb:
    container_name: influxdb
    restart: unless-stopped
    image: influxdb
    volumes:
      - ${WORKDIR}/docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ${WORKDIR}/docker/influxdb/db:/var/lib/influxdb
    environment:
      - 'env.influxdb'
    ports:
      - "8086:8086"
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "MQTT"
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${WORKDIR}/docker/mosquitto/data:/mosquitto/data
      - ${WORKDIR}/docker/mosquitto/config:/mosquitto/config
      - ${WORKDIR}/docker/mosquitto/mqtt/log:/mosquitto/log
    environment:
      - TZ=America/New_York
  home-assistant:
    #image: homeassistant/home-assistant:0.64.3
    image: homeassistant/home-assistant:latest
    container_name: "hass"
    restart: always
    depends_on:
      - influxdb
      - mqtt
      - postdb1
    healthcheck:
      test: ["CMD", "curl", "-f", "https://REDACTED"]
      interval: 30s
      timeout: 10s
      retries: 6
    ports:
      - "8123:8123"
    volumes:
      - ${WORKDIR}/docker/home-assistant-config:/config
      - ${WORKDIR}/docker/hass_media:/media
    environment:
      - TZ=America/LOS_ANGELES
    network_mode: "bridge"
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana
    user: "104"
    depends_on:
      - "influxdb"
    ports:
      - "3000:3000"
  amazon-dash:
    image: nekmo/amazon-dash:latest
    container_name: amazon-dash
    restart: always
    user: root
    volumes:
      - ${WORKDIR}/docker/amazon-dash/amazon-dash.yml:/config/amazon-dash.yml
    network_mode: "host"