version: '3'
services:
 # portainer:
 #E   container_name: portainer
 #   image: portainer/portainer
 #   volumes:
 #     - ${WORKDIR}/portainer:/data
 #     - /var/run/docker.sock:/var/run/docker.sock
 #   ports:
 #     - "9000:9000"
  mqtt:   
    #image: eclipse-mosquitto:latest
    image: fstehle/rpi-mosquitto
    container_name: "MQTT"
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${WORKDIR}/docker/mosquitto/data:/mosquitto/data
      - ${WORKDIR}/docker/mosquitto/config:/mosquitto/config
      - ${WORKDIR}/docker/mosquitto/mqtt/log:/mosquitto/log
    environment:
      - TZ=America/New_York
  home-assistant:
    #image: homeassistant/home-assistant:0.64.3
    #image: homeassistant/home-assistant:latest
    image: homeassistant/raspberrypi3-homeassistant 
  #image: lroguet/rpi-home-assistant 
    container_name: "hass"
    restart: always
    depends_on:
      - mqtt
    healthcheck:
      test: ["CMD", "curl", "-f", "https://REDACTED"]
      interval: 30s
      timeout: 10s
      retries: 6
    ports:
      - "8123:8123"
    volumes:
      - ${WORKDIR}/docker/home-assistant-config:/config
      - ${WORKDIR}/docker/hass_media:/media
    environment:
      - TZ=America/LOS_ANGELES
    network_mode: "host"
  amazon-dash:
    # image: clemenstyp/dasher-docker
    image: nekmo/amazon-dash
    container_name: amazon-dash
    restart: always
    user: root
    volumes:
      - ${WORKDIR}/docker/amazon-dash/amazon-dash.yml:/config/amazon-dash.yml
    network_mode: "host"
  motion:
    container_name: "motion"
    #image: motion:latest
    image: lazyatom/rpi-motion
    volumes:
      - ${WORKDIR}/docker/rpi-motion/:/mnt/motion/
    devices:
      - /dev/video0:/dev/video0
    ports:
      - "8081:8081"
    restart: always
