version: '3'
services:
  mqtt:   
    image: eclipse-mosquitto:latest
    container_name: "MQTT"
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/log:/mosquitto/log
    environment:
      - TZ=America/New_York

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: "hass"
    restart: unless-stopped
    depends_on:
      - mqtt
    ports:
      - "8123:8123"
    volumes:
      - ./docker/ha/ha-config:/config
      - ./docker/ha/ha-media:/media
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=America/Los_Angeles
    network_mode: "host"
